### ISSUE TITLE
Can a V100 be used for training?

### ISSUE THREAD

**Issue by liuqigui** [dvl-tum/SUSHI#1]
Can a V100 be used for training?

**Comment by liuqigui** [comment]
When will the code be released?

**Comment by ocetintas** [comment]
We haven't tested it specifically with V100 but in theory, this should be possible. 

The code will be released very soon in the upcoming days.

**Comment by liuqigui** [comment]
Okay, looking forward to the code very much. Also, may I ask what are your experimental hardware parameters? I didn't see it mentioned in the paper.

**Comment by ocetintas** [comment]
Code is online!

We used Quadro RTX 8000 for the experiments.
