### ISSUE TITLE
There are 4 levels in paper while 9 levels in code.

### ISSUE THREAD

**Issue by WesLee88524** [dvl-tum/SUSHI#12]
Hi,
The SUSHI levels in paper are 4 like [5,25,75,150] and the frames range 150.
But in the released code, there are 9 levels and the frames range 512.
So, how many levels are the models trained indeedly in the paper?

**Comment by ocetintas** [comment]
There are 9 levels both in the paper and the released code. Please check the latest version of the paper: https://openaccess.thecvf.com/content/CVPR2023/papers/Cetintas_Unifying_Short_and_Long-Term_Tracking_With_Graph_Hierarchies_CVPR_2023_paper.pdf
