### ISSUE TITLE
Weight sharing between levels

### ISSUE THREAD

**Issue by WesLee88524** [dvl-tum/SUSHI#14]
Hi Orcun,
I have a question about weight sharing between levels. You said "SUSHI blocks use the same GNN architecture at every hierarchy level. We observe that we can share parameters and learnable weights among the GNNs used for each SUSHI block." in paper. But why train the different layers independent and use different params  in code ?

**Comment by ocetintas** [comment]
We indeed share weights between levels. Please check https://github.com/dvl-tum/SUSHI/blob/main/src/models/hiclnet.py#L21. We use all_but_first setting because 'motion' features are not available for the very first level.
