### ISSUE TITLE
Zero_nodes option 

### ISSUE THREAD

**Issue by ishaybee** [dvl-tum/SUSHI#16]
Hi
I see that if zero_nodes option is used you ignore the precomputed node embeddings.
Is it correct? Is there a reason to use the pre computed node embeddings? Are they equal to the Reid embeddings?

**Comment by ocetintas** [comment]
It's true that we ignore node embeddings in the graph. Depending on the config, node and reid embeddings can be the same or obtained from different levels of the network.
