### ISSUE TITLE
Release 4 level SUSHI trained models

### ISSUE THREAD

**Issue by WesLee88524** [dvl-tum/SUSHI#17]
Hi, Ocetintas:
Because of my Nvidia card's memory, I can't train SUSHI model with 9 level. Can you release your 4 level SUHSI pretrained models for me to reproduce and compare?
Many thx!

**Comment by ocetintas** [comment]
Hi,
We are not planning to release more models but you can easily train a SUSHI with different levels by changing a couple of config variables. I'd suggest trying one of the models in Figure 4b of our paper, as we already report results there.
