### ISSUE TITLE
How can I reproduce the detection results

### ISSUE THREAD

**Issue by WesLee88524** [dvl-tum/SUSHI#18]
Hi, 
Sorry to disturb you again.
Does 'a YOLOX detector [13] trained following [77].' means you directly consider the bytetrack results as the input of SUSHI?
![image](https://github.com/dvl-tum/SUSHI/assets/25226447/8613e2c3-9c4f-4e87-b872-d614e81929fd)

**Comment by ocetintas** [comment]
No, one should disable all the tracking components of bytetrack and only use their detection backbone. You can find the detections in the repo.
