### ISSUE TITLE
Pretrained model weights for 7 level / 128 frames config

### ISSUE THREAD

**Issue by mkoshkina** [dvl-tum/SUSHI#25]
Hi,

I am trying to fine-tune the model on a different dataset but running into CUDA memory issues that others have reported. Switching to 7 levels / 128 frames configuration resolves the memory issue but prevents me from using the pretrained model.  Would you happen to have pretrained model weights for 128 frame configuration that you can share?

Thank you.

**Comment by ocetintas** [comment]
Sorry for the late reply, just saw this! The good thing is you can simply use the pretrained weights of SUSHI for 512 frames. Because, every layer (except the first one) shares weights anyways. So simply load our pretrained model and run it for 7 hierarchy levels. 

Best,
Orcun
