### ISSUE TITLE
Training Command Correction

### ISSUE THREAD

**Issue by mseok7797** [dvl-tum/SUSHI#26]
According to the Readme, there's a mistake in the command line for the Training part. Instead of using "byte065", it should be corrected to "det".

--det_file byte065 -> --det_file det

**Comment by ocetintas** [comment]
This is optional and depends on which detection set you want to use. If you want to reproduce private benchmark results reported in our paper, please use byte065 setting. Otherwise, you are free to use any set of detections

**Comment by mseok7797** [comment]
Thanks for your reply.
I'd like to train a model with custom yolo datasets.
Could you provide some guidance on tasks to reference for training with custom data?
