### ISSUE TITLE
What is my pretrained model?

### ISSUE THREAD

**Issue by mseok7797** [dvl-tum/SUSHI#27]
Thank you for sharing your code and work.

I trained the model with a 7-layer hierarchical structure using the provided code.

However, I'm unsure about the 'PRETRAINED_MODEL_PATH=your_pretrained_model_path' part in the test execution command.

Could you please provide guidance on this?

Below is the command I used for training with 7 layers. Should I also include this setting in the test execution command?
![2024-04-29 184736](https://github.com/dvl-tum/SUSHI/assets/67899924/c2c1f4de-c15a-42a0-ac97-a3efe2faac5b)

**Comment by ocetintas** [comment]
This is either the path of the pretrained models provided by us or the path of the model you've trained
