### ISSUE TITLE
Tracking in a "live" scenario

### ISSUE THREAD

**Issue by finlay96** [dvl-tum/SUSHI#4]
Hi there, 

I was wondering if this approach would work for a "live"/online approach. Such that there is a buffer of X past frames and then the tracker outputs a stable result for each subsequent frame with the buffer working in a FIFO method. Do you believe this would work or does this method require future information to work effectively?

Thanks!

**Comment by ocetintas** [comment]
Hi, 
This is indeed possible but note that future information is helpful for tracking and dropping those frames would result in slightly lower tracking scores.
