### ISSUE TITLE
support single object tracking?

### ISSUE THREAD

**Issue by jcyhcs** [dvl-tum/SUSHI#9]
i  noticed that your evaluation all in multi-objects tracking datasets, i want to know this algorithm can use in single object tracking? please help me?

**Comment by ocetintas** [comment]
Hi,
If there is a single object in the scene our model can, of course, track it. Other than this, you can implement simple preprocessing and postprocessing scripts to ensure that detections and predictions never includes more than a single identity if this is an important condition for you.
